apiVersion: v1
kind: List
items: 
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: alpha-example
    name: alpha-example
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: alpha-example
    name: alpha-example
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: alpha-example:latest
    source:
      contextDir: HelloWorld
      git:
        ref: master
        uri: http://gogs.cloudapps.example.com/gogs/uberjar.git
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: alpha-test:latest
          namespace: alpha
      incremental: true
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange

