apiVersion: v1
kind: List
items: 
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: alpha
    name: alpha-output
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: alpha
    name: alpha
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: alpha-output:latest
    source:
      contextDir: HelloWorld
      git:
        ref: master
        uri: http://gogs.cloudapps.example.com/gogs/uberjar.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
        forcePull: true
        from:
          kind: ImageStreamTag
          name: alpha-base:latest
          namespace: alpha
        incremental: true
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange

